name: deployment

on:
  push:
    branches: [ "master" ]

run-name: deployment

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Information
        run: |
          echo "Triggered by:  ${{ github.triggering_actor }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Deploy GitHub Pages site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./dist